### ISSUE TITLE
Add Recommended Metric/Span `instrumentation.provider` and `collector.name` Attributes

### ISSUE THREAD

**Issue by MrAlias** [newrelic/newrelic-opencensus-exporter-python#7]
In order to identify the source of telemetry sent from this exporter the following attributes should be added to all spans and metrics emitted.

- `instrumentation.provider`: `opencensus`
   - This attribute identifies the instrumentation source of the telemetry.
- `collector.name`: `newrelic-opencensus-python-exporter`
   - This attributes identifies the exporter that emitted the spans and metrics.

The attribute keys are specified in [the New Relic exporter specification](https://github.com/newrelic/newrelic-exporter-specs/blob/master/Guidelines.md#common-patterns), but the values are suggestions based on prior-art of [what was done in the Go exporter](https://github.com/newrelic/newrelic-opencensus-exporter-go/pull/8).

**Comment by Ak-x** [comment]
This will be prioritized into a broader documentation effort that we are undertaking on our upcoming roadmap.

**Comment by umaannamalai** [comment]
Closing issue as part of this repo's archival process.
